export const LOGIN_SER_PROVIDER='LOGIN_SER_PROVIDER'
export const LOGOUT_SER_PROVIDER='LOGOUT_SER_PROVIDER'
export const REGISTER_SER_PROVIDER='REGISTER_SER_PROVIDER'
export const GET_SERVICES='GET_SERVICES'
